### ISSUE TITLE
Tests can't compile due to rayon MSRV update without new minor bump

### ISSUE THREAD

**Issue by CPerezz** [zkcrypto/bls12_381#112]
If you try to run the tests for this lib, you'll see that you get:

`error: package `rayon-core v1.11.0` cannot be built because it requires rustc 1.59 or newer, while the currently active rustc version is 1.56.0`

This is due to the fact that:
```
❯ cargo tree -i rayon-core       
rayon-core v1.11.0
└── rayon v1.7.0
    └── criterion v0.3.6
        [dev-dependencies]
        └── bls12_381 v0.8.0 
```

As you can see here, `criterion` depends on `rayon_core` with `^0.3`. After `rayon` moved up MSRV without bumping minor version, everything broke.

We might want to either:
- Bump MSRV.
- Fix Cargo.lock (doesn't make any sense to me as this is a lib).
- Downgrade Criterion in hopes it uses a version of `rayon` compatible with `rustc 1.56.0` or older.

@str4d let me know what you prefer and I'll push a PR.

**Comment by CPerezz** [comment]
After bumping to `1.59`, I saw the following:
`error: package `regex-syntax v0.7.2` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.59.0`

```
cargo tree -i regex-syntax
regex-syntax v0.7.2
└── regex v1.8.4
    └── criterion v0.3.6
        [dev-dependencies]
        └── bls12_381 v0.8.0
```

It seems same thing happened as with `rayon_core`. Bumping to `1.60.0` solves all the issues.

**Comment by HDauven** [comment]
I'm not sure what version `rayon-core` is set at, but from `v1.12.0` it requires at least rustc `1.63`. 

It would be nice if either your PR #113 and #116 were applied, or the versions locked.

**Comment by str4d** [comment]
> - Fix Cargo.lock (doesn't make any sense to me as this is a lib).

As of just over a week prior to this issue being opened, [the recommendation for libraries is now to check in `Cargo.lock` if you are trying to maintain an MSRV](https://blog.rust-lang.org/2023/08/29/committing-lockfiles). I did this in #135, and tests now work again.
