### ISSUE TITLE
Acceptable encoding of infinite points

### ISSUE THREAD

**Issue by randombit** [zkcrypto/bls12_381#122]
The current serialization notes (https://github.com/zkcrypto/bls12_381/blob/main/src/notes/serialization.rs#L23-L25) state that for points with infinity bit set "the remaining bits of the group element's encoding should be set to zero."

Is this a should in the "SHOULD" sense of RFC 2119; a behavior that is preferential but can be ignored if useful? Or is it an informal statement of a strict requirement (aka a "MUST")? This crate seems to strictly require that if the infinity bit is set that all other bits are zeroed.

**Comment by str4d** [comment]
It's the latter, an informal statement of an RFC 2119 MUST. We require canonical encodings of group elements in this crate.
