### ISSUE TITLE
Support Zeroize

### ISSUE THREAD

**Issue by afck** [zkcrypto/bls12_381#14]
Cryptographic applications should be able to wipe sensitive data from memory before deallocating it. E.g. the elements of `Fr` [can be used](https://github.com/poanetwork/threshold_crypto/blob/624eeee7e4ac5e565abbe93a31580a8f806ee5c4/src/lib.rs#L298) as secret [BLS keys](https://en.wikipedia.org/wiki/Boneh%E2%80%93Lynn%E2%80%93Shacham).

Without support from the bls12_381 crate itself, [any attempt to clear](https://github.com/poanetwork/threshold_crypto/blob/624eeee7e4ac5e565abbe93a31580a8f806ee5c4/src/secret.rs#L9) such data necessarily depends on an implementation detail of bls12_381 that is not part of the public API, e.g. `Fr` not using any pointers internally.

The safest way to support this would be to add explicit methods for clearing, or to [`impl Zeroize for Fr`](https://docs.rs/zeroize/1.0.0/zeroize/trait.Zeroize.html). If the added [zeroize](https://crates.io/crates/zeroize) dependency is a concern, it could be made optional, and put behind a feature flag.

**Comment by ebfull** [comment]
Thanks! I love `zeroize` and definitely think we should support it.
