### ISSUE TITLE
Bump version and republish on crates.io

### ISSUE THREAD

**Issue by narodnik** [zkcrypto/bls12_381#30]
I cannot find clear_cofactor() method which was recently added when using crates.io... getting compiler messages.

**Comment by narodnik** [comment]
Guys, please close the pull request and bump the version. Otherwise I'll have to make a fork of your package on crates.io

**Comment by str4d** [comment]
The PR has been blocked on review, and I've been off work until this week. I'll aim to get to it this week.

**Comment by ebfull** [comment]
@narodnik 0.1.1 has been pushed to crates.io.

**Comment by ebfull** [comment]
BTW if you want to actually use the endomorphism for clearing the cofactor you need to enable the `endo` crate feature. Otherwise it will merely pretend to use the endomorphism internally, to avoid potential patent issues.
