### ISSUE TITLE
How can I multiply elements in Gt with another Gt?

### ISSUE THREAD

**Issue by vihu** [zkcrypto/bls12_381#68]
I was trying to implement https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-2.9. The algorithm is:

```
   1.  R = signature_to_point(signature)
   2.  If R is INVALID, return INVALID
   3.  If signature_subgroup_check(R) is INVALID, return INVALID
   4.  C1 = 1 (the identity element in GT)
   5.  for i in 1, ..., n:
   6.      If KeyValidate(PK_i) is INVALID, return INVALID
   7.      xP = pubkey_to_point(PK_i)
   8.      Q = hash_to_point(message_i)
   9.      C1 = C1 * pairing(Q, xP)
   10. C2 = pairing(R, P)
   11. If C1 == C2, return VALID, else return INVALID
```

I'm stuck on line#9, the current code allows multiplying Gt * Scalar (if I'm reading the code correctly); is there a way to do Gt * Gt?

Thanks!
Specifically line#9;

**Comment by burdges** [comment]
I doubt this crate cares much about BLS signatures per se, so maybe discuss this some where more relevant.  That said..

It's faster if you do all the pairings inside one Miller loop, which is equivalent to multiplying the results, and then only run the final exponentiation once when done.  It's honestly kinda ridiculous for an IRTF CFRG draft to propose doing multiplications in the target group like that.  lol

In fact, BLS signature verification should _never_ resemble that loop anyways.  Instead, either many/all Q should be repeated or else many/all PK_i should be repeated, in which case you reduce the Miller loops by bi-linearity.

**Comment by vihu** [comment]
> I doubt this crate cares much about BLS signatures per se, so maybe discuss this some where more relevant. That said..
> 
> It's faster if you do all the pairings inside one Miller loop, which is equivalent to multiplying the results, and then only run the final exponentiation once when done. It's honestly kinda ridiculous for an IRTF CFRG draft to propose doing multiplications in the target group like that. lol
> 
> In fact, BLS signature verification should _never_ resemble that loop anyways. Instead, either many/all Q should be repeated or else many/all PK_i should be repeated, in which case you reduce the Miller loops by bi-linearity.

Thank you very much for the hint @burdges :raised_hands: . I have opened #69, it does indeed work in my [testing](https://github.com/vihu/rust-tc/blob/main/src/sig.rs#L79).
